### ISSUE TITLE
Onde está o concern?

### ISSUE THREAD

**Issue by paulopatto** [psidneis/epl_api#1]
Olá vejo que essa não é uma aplicação séria, já que não tem uma "pá" de concerns.

Está fora do padrão!

**Comment by psidneis** [comment]
@paulopatto tem exemplos?

**Comment by paulopatto** [comment]
Os exemplos que possuo são privados e enterprise, não sei se você manja disso! 

Mas acredito um concern do jobs_controller poderia ser o `JobeableShared`

**Comment by psidneis** [comment]
@paulopatto fuckableIdea, vou fazer!
